/* Public archived decision and simulated trajectory explorer. No engine internals. */
const AHA = (()=>{
 let ledger=[],trials=[],ready=false,timer=null;
 const section=document.getElementById('experience');
 const number=v=>Number(v).toLocaleString(undefined,{maximumFractionDigits:2});
 function stop(){clearInterval(timer);timer=null;const b=document.getElementById('play');if(b)b.textContent='Play';}
 function metrics(cards){return '<div class="metrics">'+cards.map(([name,left,right,unit])=>'<div class="metric"><span>'+name+'</span><strong>'+number(left)+' <small>→</small> '+number(right)+'</strong><em>'+unit+'</em></div>').join('')+'</div>'}
 function chart(series,ylabel,maxValue,limit){
  const width=850,height=220,left=60,top=15,bottom=35,plotW=width-left-20,plotH=height-top-bottom;
  const all=series.flatMap(x=>x.values);let max=maxValue||Math.max(...all,1),min=0;
  const n=Math.max(...series.map(x=>x.values.length),2)-1;
  let s='<svg viewBox="0 0 '+width+' '+height+'" role="img" aria-label="'+ylabel+' comparison"><text x="60" y="12">'+ylabel+'</text>';
  for(let i=0;i<4;i++){let y=top+plotH*i/3;s+='<line x1="'+left+'" y1="'+y+'" x2="830" y2="'+y+'" stroke="#d8e2ee"/><text x="4" y="'+(y+5)+'">'+number(max*(1-i/3))+'</text>'}
  if(limit){let y=top+plotH*(1-limit/max);s+='<line x1="60" y1="'+y+'" x2="830" y2="'+y+'" stroke="#c45252" stroke-dasharray="5 5"/><text x="630" y="'+(y-5)+'">Safety boundary '+limit+'</text>'}
  for(const line of series){let points=line.values.map((v,i)=>(left+i/n*plotW)+','+(top+(1-v/max)*plotH)).join(' ');s+='<polyline fill="none" stroke="'+line.color+'" stroke-width="3" points="'+points+'"/>'}
  s+='<text x="60" y="213">Start</text><text x="750" y="213">Current step</text></svg>';return s;
 }
 function controls(max,title){return '<div class="controls"><button id="play">Play</button><button id="finish">Show full result</button><label>'+title+' <input id="position" type="range" min="0" max="'+max+'" value="'+max+'"></label><output id="positiontext"></output></div>'}
 function wire(max,draw){const slider=document.getElementById('position');slider.oninput=()=>{stop();draw(+slider.value)};document.getElementById('finish').onclick=()=>{stop();slider.value=max;draw(max)};document.getElementById('play').onclick=()=>{if(timer){stop();return}if(+slider.value===max)slider.value=0;document.getElementById('play').textContent='Pause';timer=setInterval(()=>{let p=Math.min(max,+slider.value+(max>100?80:1));slider.value=p;draw(p);if(p===max)stop()},max>100?50:140)};draw(max)}
 function scania(){
  section.innerHTML='<h2>Same failures detected. Fewer heavy evaluations.</h2><p>Follow the actual decision ledger, in dataset row order. Blue: always-on baseline. Gold: gated evaluation.</p>'+controls(ledger.length,'Records reviewed')+'<div id="counters"></div><div id="graph"></div><p id="takeaway" class="takeaway"></p><label>Inspect record <input id="record" type="number" min="1" max="16000" value="1"></label><div id="recorddetail" class="record"></div><p class="limit">Archived decision replay. These are recorded routing decisions, not live model execution or measured electricity savings. Dataset row order is not a time series.</p>';
  function draw(n){let bf=0,gf=0,bp=0,gp=0,calls=0;const step=Math.max(1,Math.floor(n/120)),b=[],g=[];for(let i=0;i<n;i++){const[y,c,bpred,gpred]=ledger[i];calls+=c;bf+=y&&!bpred;gf+=y&&!gpred;bp+=!y&&bpred;gp+=!y&&gpred;if(i%step===0||i===n-1){b.push(i+1);g.push(calls)}}document.getElementById('positiontext').textContent=number(n)+' / 16,000';document.getElementById('counters').innerHTML=metrics([['Heavy evaluations',n,calls,'Recorded routing'],['Missed failures',bf,gf,'Labelled failures'],['False positives',bp,gp,'False alarms'],['Modeled cost',10*bp+500*bf,10*gp+500*gf,'10 per false positive, 500 per missed failure']]);document.getElementById('graph').innerHTML=chart([{values:b,color:'#367de0'},{values:g,color:'#bc8216'}],'Cumulative heavy evaluations',Math.max(n,1));document.getElementById('takeaway').textContent=n===16000?'13,708 heavy evaluations avoided, 85.675%, with the same six failures missed and 101 fewer false positives in this locked test.':number(n-calls)+' recorded heavy evaluations avoided so far. Compare the outcomes alongside the reduction.';}
  const input=document.getElementById('record');function detail(){const i=Math.max(0,Math.min(15999,Math.floor(+input.value||1)-1));input.value=i+1;const[y,c,b,g]=ledger[i];document.getElementById('recorddetail').textContent='Record '+(i+1)+' · Actual: '+(y?'failure':'non-failure')+' · Gate: '+(c?'call heavy model':'bypass')+' · Baseline: '+(b?'failure':'non-failure')+' · Gated: '+(g?'failure':'non-failure');}input.oninput=detail;detail();wire(ledger.length,draw);
 }
 function hbi(){
  const chosen=filter.value==='all'?'1':filter.value;const pair=trials.filter(x=>String(x.scenario)===chosen);const base=pair.find(x=>x.policy==='bellman'),event=pair.find(x=>x.policy==='event_v041');if(!base||!event){section.textContent='Scenario trajectories unavailable';return}
  section.innerHTML='<h2>Watch two controllers handle the same disturbance.</h2><p>Scenario '+chosen+' · '+base.mode.replaceAll('_',' ')+' · Blue: Bellman. Gold: event controller. Choose another scenario using the filter above.</p>'+controls(48,'Simulation step')+'<div id="counters"></div><div id="thermal"></div><div id="effort"></div><div id="energy"></div><p id="takeaway" class="takeaway"></p><p class="limit">Original frozen synthetic simulation using benchmark proxy operators. Energy is in model units, not kWh. Every captured trial result matched its archived row; this is local reproduction, not outside validation.</p>';
  function draw(n){const b=base.frames.slice(0,n),e=event.frames.slice(0,n),last=x=>x.at(-1)||{energy:0,commands:0,active:0};const bl=last(b),el=last(e);document.getElementById('positiontext').textContent=n+' / 48';document.getElementById('counters').innerHTML=metrics([['Cumulative modeled energy',bl.energy,el.energy,'Simulation units'],['Command events',bl.commands,el.commands,'Started interventions'],['Active control steps',bl.active,el.active,'Applied effort > 0.05']]);for(const[id,key,title,max,limit]of [['thermal','hotspot','Hotspot temperature (°C)',42,36],['effort','action','Applied control effort',1.5,null],['energy','energy','Cumulative modeled energy',100,null]])document.getElementById(id).innerHTML=chart([{values:b.map(x=>x[key]),color:'#367de0'},{values:e.map(x=>x[key]),color:'#bc8216'}],title,max,limit);document.getElementById('takeaway').textContent=n===48?'Both policies survived this scenario with zero safety violations. Event control used '+number(100*(1-event.result.total_energy/base.result.total_energy))+'% less modeled energy. Across all 72 cases: 20.2% lower mean modeled energy.':'Watch control activity and energy accumulate while comparing thermal protection.';}
  wire(48,draw);
 }
 function models(){
  let names=[...new Set(DATA.models.map(x=>x.model))];let name=filter.value==='all'?'Extra Trees':filter.value;let b=DATA.models.find(x=>x.model===name&&x.configuration==='Full model on every record'),g=DATA.models.find(x=>x.model===name&&x.configuration!=='Full model on every record');const pass=g.passes_operational_gate==='True';section.innerHTML='<h2>Efficiency matters when outcomes hold up.</h2><p>Select a model above. Each comparison uses the same 16,000-row official test population.</p>'+metrics([['Heavy evaluations',+b.full_model_calls,+g.full_model_calls,'Recorded calls'],['Missed failures',+b.false_negatives,+g.false_negatives,'Critical outcome'],['Modeled cost',+b.modeled_cost,+g.modeled_cost,'Benchmark cost units']])+'<p class="takeaway '+(pass?'':'fail')+'">'+name+': '+(pass?'PASS':'DID NOT PASS')+'. '+number(+g.full_model_call_reduction_pct)+'% fewer calls, '+number(+g.relative_cost_change_pct)+'% cost change, '+g.missed_failure_change+' additional missed failures.</p><p>Frozen gate: ≥25% fewer calls, ≤2% higher modeled cost and ≤1 additional missed failure. Eight models pass; MLP fails despite its largest call reduction.</p><button id="mlp">Inspect the MLP failure</button><p class="limit">Aggregate benchmark evidence. Nine complete executable model packages remain unavailable. Equal missed-failure counts alone do not establish identical missed records.</p>';document.getElementById('mlp').onclick=()=>{filter.value='MLP Neural Network';render();refresh()};
 }
 function refresh(){stop();document.getElementById("result").parentElement.hidden=false;if(!ready){section.textContent='Loading recorded outputs…';return}if(track.value==='scania')scania();else if(track.value==='hbi')hbi();else if(track.value==='model-families')models();else if(window.TRACKS)window.TRACKS.render(track.value);else section.textContent='Loading track evidence…';}
 async function init(){try{const res=await Promise.all([fetch('scania_decisions.json'),fetch('hbi_trajectories.json')]);if(res.some(x=>!x.ok))throw Error('Output files unavailable');const data=await Promise.all(res.map(x=>x.json()));ledger=data[0].rows;trials=data[1].trials;ready=true;const old=track.onchange;track.onchange=()=>{old();refresh()};filter.onchange=()=>{render();refresh()};track.value='scania';change();refresh();}catch(e){section.textContent='The recorded outputs could not load. Refresh the page or use the source evidence link.'}}
 return {init,refresh};
})();
AHA.init();
