window.TRACKS=(()=>{
const section=document.getElementById('experience');let evidence={};
const fmt=v=>Number(v).toLocaleString(undefined,{maximumFractionDigits:3});
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function bars(rows,key,max){return rows.map(r=>'<div class="barrow"><span>'+escape(r.label)+'</span><div class="bartrack"><div style="width:'+Math.max(0,Math.min(100,100*r[key]/max))+'%"></div></div><strong>'+fmt(r[key])+'</strong></div>').join('')}
function nasa(){let ds=filter.value==='all'?'FD002':filter.value;section.innerHTML='<h2>Compare detection with the cost of false alerts.</h2><p>Archived results from NASA C-MAPSS datasets. These are comparisons on NASA data, not comparisons against NASA as an organization.</p><div class="controls"><label>Dataset <select id="dataset">'+['FD002','FD003','FD004'].map(v=>'<option '+(v===ds?'selected':'')+'>'+v+'</option>').join('')+'</select></label><label>Warning horizon <select id="horizon">'+[20,30,50].map(v=>'<option>'+v+'</option>').join('')+'</select></label><label>Metric <select id="metric"><option>F1</option><option>Detection %</option><option>False alerts / engine</option><option>Mean first-alert RUL</option><option>Precision</option><option>Recall</option></select></label></div><div id="nasabars"></div><p id="nasainsight" class="takeaway"></p><p class="limit">Historical aggregate outputs, with recovered source-file hashes verified. Higher is better for F1, precision, recall and detection. Lower is better for false alerts. First-alert RUL must be interpreted with detection and false-alert burden. No new engine execution or individual-engine trajectory is shown.</p>';
function draw(){const ds=document.getElementById('dataset').value,h=document.getElementById('horizon').value,m=document.getElementById('metric').value;const rows=Object.entries(DATA.nasa).filter(([k])=>k.includes(ds)).flatMap(([k,v])=>v).filter(r=>String(r['RUL horizon'])===h).map(r=>({label:r.Method,value:+r[m]}));document.getElementById('nasabars').innerHTML=bars(rows,'value',Math.max(...rows.map(r=>r.value),1));const ordered=[...rows].sort((a,b)=>m==='False alerts / engine'?a.value-b.value:b.value-a.value);document.getElementById('nasainsight').textContent=ordered[0].label+' has the '+(m==='False alerts / engine'?'lowest':'highest')+' '+m+' at this horizon. Switch metrics to inspect the tradeoffs.';}
['dataset','horizon','metric'].forEach(k=>document.getElementById(k).onchange=draw);draw();}
function fallback(id){section.innerHTML='<h2>'+escape(id)+' evidence</h2><p>Recovering the original evidence for this view.</p>';}
function render(id){document.getElementById('result').parentElement.hidden=true;if(id==='nasa')nasa();else if(evidence[id]&&window['render_'+id.replaceAll('-','_')])window['render_'+id.replaceAll('-','_')](evidence[id],section,bars,fmt,escape);else fallback(id);}
async function load(){for(const id of ['fraud','ecg','uci-power','optical','training-free-ai']){try{const r=await fetch(id+'_evidence.json');if(r.ok)evidence[id]=await r.json()}catch(e){}}AHA.refresh();}
return {render,load};})();
TRACKS.load();
