window.render_uci_power=(d,s,bars,fmt,esc)=>{
s.innerHTML='<h2>Explore four years of recorded monthly patterns.</h2><p>34,190 hourly readings summarized into 1,418 windows in the historical analysis.</p><label>Year <select id="powerYear"><option>all</option>'+[2006,2007,2008,2009,2010].map(y=>'<option>'+y+'</option>').join('')+'</select></label><div id="powerbars"></div><p class="takeaway">432 Coherence Engine alerts and 1 variance alert were reported. More alerts establish different detector behavior; they do not establish better detection without verified event labels.</p><p class="limit">'+esc(d.scope)+'</p><a class="evidence-link" href="uci-power.html">Read power research summary</a>';
function draw(){const y=document.getElementById('powerYear').value;document.getElementById('powerbars').innerHTML=bars(d.monthly.filter(r=>y==='all'||r.month.startsWith(y)).map(r=>({label:r.month+' · '+r.level,value:r.mean_delta})),'value',1.1)}document.getElementById('powerYear').onchange=draw;draw();};
window.render_optical=(d,s,bars,fmt,esc)=>{
s.innerHTML='<h2>See what survives common-mode removal.</h2><p>Six optical bases, three recorded representations, one frozen test. The failed result is preserved.</p><label>Representation <select id="optRep">'+['raw','global_sum_normalized','pair_normalized'].map(v=>'<option>'+v+'</option>').join('')+'</select></label><div id="optRows"></div><p id="optInsight" class="takeaway fail"></p><p class="limit">Recorded aggregate comparison, not waveform playback. The observation axis was optical delay, not elapsed time. Raw channel samples were not recovered. A failed test limits this specific replication claim; it does not erase separate computational benchmark results.</p>';
function draw(){const rep=document.getElementById('optRep').value;const r=d.rows.filter(x=>x.representation===rep);document.getElementById('optRows').innerHTML='<div class="scroll"><table><tr><th>Basis</th><th>Observed statistic</th><th>Surrogate median</th><th>Disappearance %</th><th>Frozen gate</th></tr>'+r.map(x=>'<tr><td>'+esc(x.basis)+'</td><td>'+fmt(x.observed_cf)+'</td><td>'+fmt(x.surrogate_median)+'</td><td>'+fmt(100*x.drop)+'</td><td>FAIL, requires ≥50%</td></tr>').join('')+'</table></div>';document.getElementById('optInsight').textContent=d.explanation[rep]+' All representations were required to pass; the overall frozen result remains FAIL.';}document.getElementById('optRep').onchange=draw;draw();};
window.render_ecg=(d,s,bars,fmt,esc)=>{
s.innerHTML='<h2>Compare ECG tradeoffs, study by study.</h2><label>Study <select id="ecgStudy">'+d.studies.map((x,i)=>'<option value="'+i+'">'+esc(x.title)+'</option>').join('')+'</select></label><label>Metric <select id="ecgMetric"><option>f1</option><option>precision</option><option>recall</option></select></label><div id="ecgResults"></div><p id="ecgInsight" class="takeaway"></p><p class="limit">'+esc(d.scope)+' Original scored windows, event rules and patient mapping remain unavailable. Aggregate comparisons do not establish predictive warning or clinical performance.</p><a class="evidence-link" href="ecg.html">Read ECG research summary</a>';
function draw(){const x=d.studies[+document.getElementById('ecgStudy').value],m=document.getElementById('ecgMetric').value;document.getElementById('ecgResults').innerHTML=x.rows?bars(x.rows.map(r=>({label:r.method,value:r[m]})),'value',1):'<p>'+x.records_processed+' records processed · mean '+esc(m)+' '+fmt(x['mean_'+m])+'</p>';document.getElementById('ecgInsight').textContent=x.takeaway||x.interpretation;}['ecgStudy','ecgMetric'].forEach(k=>document.getElementById(k).onchange=draw);draw();};
window.render_fraud=(d,s,bars,fmt,esc)=>{
let timer=null;s.innerHTML='<h2>Inspect fraud windows and the missed detections.</h2><p>Chronological development audit, each window contains 500 transactions. This recovered audit is separate from the earlier overlapping-window summary.</p><div class="controls"><label>Method <select id="fraudMethod">'+Object.keys(d.methods).map(k=>'<option>'+k+'</option>').join('')+'</select></label><button id="fraudPlay">Play</button><label>Windows reviewed <input id="fraudPosition" type="range" min="0" max="469" value="469"></label><output id="fraudCount"></output></div><div id="fraudCounters"></div><div id="fraudCells" class="cells"></div><label>Inspect window <input id="fraudRecord" type="number" min="1" max="469" value="1"></label><p id="fraudDetail"></p><p class="takeaway fail">The original fixed method raised zero alerts and missed all 186 fraud-containing test windows. Development candidates and comparators also had low recall. These failures remain visible.</p><p class="limit">'+esc(d.scope)+'</p>';
const method=document.getElementById('fraudMethod'),slider=document.getElementById('fraudPosition');function stop(){clearInterval(timer);timer=null;const el=document.getElementById('fraudPlay');if(el)el.textContent='Play'}
function detail(){const input=document.getElementById('fraudRecord');const i=Math.max(0,Math.min(468,Math.floor(+input.value||1)-1)),r=d.rows[i];document.getElementById('fraudDetail').textContent='Window '+r.index+' · dataset rows '+r.start_row+'–'+r.end_row+' · '+r.fraud_count+' fraud transactions · '+(r.alerts[method.value]?'Alert':'No alert');}
function draw(){const n=+slider.value,k=method.value;let tp=0,fp=0,fn=0,tn=0;d.rows.slice(0,n).forEach(r=>{if(r.contains_fraud){if(r.alerts[k])tp++;else fn++}else{if(r.alerts[k])fp++;else tn++}});document.getElementById('fraudCount').textContent=n+' / 469';document.getElementById('fraudCounters').innerHTML=bars([{label:'Detected fraud windows',value:tp},{label:'Missed fraud windows',value:fn},{label:'False alerts',value:fp},{label:'Correct quiet windows',value:tn}],'value',469);document.getElementById('fraudCells').innerHTML='<p>Green: detected fraud · Red: missed fraud · Gold: false alert · Gray: correct quiet</p>'+d.rows.slice(0,n).map(r=>'<button class="cell '+(r.contains_fraud?(r.alerts[k]?'tp':'fn'):(r.alerts[k]?'fp':'tn'))+'" data-index="'+r.index+'" title="Window '+r.index+'" aria-label="Inspect window '+r.index+'">'+r.index+'</button>').join('');document.querySelectorAll('[data-index]').forEach(el=>el.onclick=()=>{document.getElementById('fraudRecord').value=el.dataset.index;detail()});detail();}
method.onchange=()=>{stop();draw()};slider.oninput=()=>{stop();draw()};document.getElementById('fraudRecord').oninput=detail;document.getElementById('fraudPlay').onclick=()=>{if(timer){stop();return}if(+slider.value===469)slider.value=0;document.getElementById('fraudPlay').textContent='Pause';timer=setInterval(()=>{if(track.value!=='fraud'){stop();return}slider.value=Math.min(469,+slider.value+5);draw();if(+slider.value===469)stop()},120)};draw();};
